services:
  eventstore:
    image: eventstore/eventstore:22.10.1-alpha-arm64v8
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_EXT_IP=0.0.0.0
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_INT_IP=0.0.0.0
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
    volumes:
      - ./data:/data
      
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=restaurant-booking

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@rb.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - pgadmin_config:/var/lib/pgadmin

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  bullboard:
    container_name: bullboard
    image: deadly0/bull-board
    restart: always
    ports:
      - 6300:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BULL_PREFIX=bull

volumes:
  pgadmin_config:

